language: bash

install:
  - sudo apt update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

before_script:
  # Create conda virtual environments
  - conda env create -f env/main.yml
  - conda env create -f env/dev.yml

script:
  # Activate the main env and test package installation
  - conda activate moranpycess && echo $CONDA_DEFAULT_ENV
  - pip install .
  # Activate the dev env and test package installation
  - conda activate moranpycess-dev && echo $CONDA_DEFAULT_ENV
  - pip install .
  # Run unit tests and measure code coverage
  - coverage run -m pytest tests/unit/Individual.py tests/unit/MoranProcess.py tests/unit/MoranProcess2D.py
  - coverage report -m

after_success:
  - conda activate moranpycess-dev && echo $CONDA_DEFAULT_ENV
  - coveralls
