###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 20-07-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: moranpycess-dev

  channels:
    - conda-forge

  dependencies:
    - black>=22.6.0
    - coverage>=6.0
    - flake8>=5.0.4
    - jupyterlab>=3.3.4
    - make>=4.3
    - matplotlib>=3.3.4
    - numpy>=1.19.5
    - pandas>=1.1.5
    - pytest>=6.2.5
    - python>=3.6.15
    - recommonmark>=0.7.1
    - scipy>=1.5.3
    - seaborn>=0.11.2
    - sphinx>=5.1.1
    - sphinx_rtd_theme>=1.2.2

...
