###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 20-07-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: moranpycess-dev

  channels:
    - bioconda
    - conda-forge
    - anaconda
    - jiayi_anaconda

  dependencies:
    - black=22.10.0 
    - coverage=7.0.0
    - flake8=6.0.0
    - jupyterlab=3.5.2
    - make=4.3
    - matplotlib=3.6.2
    - numpy=1.24.0
    - pandas=1.5.2
    - pip=22.3.1
    - pip:
      - sphinx-rtd-theme==1.1.1
    - pytest=7.2.0
    - python=3.9.15
    - recommonmark=0.7.1
    - scipy=1.9.3
    - seaborn=0.12.1
    - sphinx=5.3.0

...
