###############################################################################
#
#   conda-build recipe for the package
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 26-12-2020
#   LICENSE: MIT
#
###############################################################################
---

package:
  name: moranpycess
  version: "1.1.0"

source:
  path: .

build:
  noarch: python # require conda >=4.3 to install
  script: python -m pip install --no-deps .

channels:
  - conda-forge

requirements:
  host:
    - python>=3.9
    - pip
  run:
    - matplotlib>=3.3.4
    - numpy>=1.19.5
    - pandas>=1.1.5
    - python>=3.9
    - scipy>=1.5.3
    - seaborn>=0.11.2

test:
  imports:
    - moranpycess

about:
  home: https://angrymaciek.github.io/angry-moran-simulator/_build/html/index.html
  summary: >
    Python framework for Moran Processes driven by game theory
  description: |
    The following package presents a general game-theoretical framework
    to carry out scientific simulations according to the Moran model.
    Registering distinct types of individuals together with specification
    of payoffs between them allows to replicate evolution of the population
    and observe growth dynamics.
    For more information please visit project's homepage!
  license: MIT
  license_file: LICENSE

extra:
  maintainers:
   - Maciek Bak

...
