###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 20-07-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: moran-simulator-dev
      
  channels:
    - bioconda
    - conda-forge
      
  dependencies:
    - black=19.10b0
    - coverage=5.1
    - coveralls=2.1.1
    - flake8=3.8.3
    - jupyterlab=2.2.0
    - matplotlib=3.3.0
    - numpy=1.19.0
    - pandas=1.0.1
    - pip=20.1.1
    - pytest=5.4.3
    - python=3.7.4
    - scipy=1.5.2
    - seaborn=0.10.1
  
...
