###############################################################################
#
#   Software to be installed in the environment
#
#   AUTHOR: Maciej_Bak
#   AFFILIATION: University_of_Basel
#   AFFILIATION: Swiss_Institute_of_Bioinformatics
#   CONTACT: wsciekly.maciek@gmail.com
#   CREATED: 20-07-2020
#   LICENSE: MIT
#
###############################################################################
---

  name: moranpycess-dev

  channels:
    - bioconda
    - conda-forge
    - anaconda
    - jiayi_anaconda

  dependencies:
    - black
    - coverage
    - flake8
    - jupyterlab
    - make
    - matplotlib
    - numpy
    - pandas
    - pip
    - pip:
      - sphinx-rtd-theme
    - pytest
    - python=3.9.15
    - recommonmark
    - scipy
    - seaborn
    - sphinx

...
