name: build

on:
  push:
    branches:
      - '*'

jobs:

  PyPI-pkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v1
        with:
          python-version: 3.11

      - name: Install the Package
        run: python -m pip install .

      - name: Test Package Import
        run: python -c 'import moranpycess'

      - name: Uninstall the Package
        run: python -m pip uninstall moranpycess --yes

  conda-pkg:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          auto-activate-base: true

      - name: Install conda-build
        shell: bash -l {0}
        run: conda install conda-build

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Build Anaconda Package
        shell: bash -l {0}
        run: conda build .

      - name: Install the Package
        shell: bash -l {0}
        run: conda install -c ${CONDA_PREFIX}/conda-bld/ moranpycess --yes

      - name: Test Package Import
        shell: bash -l {0}
        run: python -c 'import moranpycess'

      - name: Uninstall the Package
        shell: bash -l {0}
        run: conda remove moranpycess
