name: docs

on:
  push:
    branches:
      - "master"

jobs:

  gh-pages:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          activate-environment: moranpycess-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Install
        shell: bash -l {0}
        run: make install

      - name: BuildTheDocs
        shell: bash -l {0}
        run: make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: 'docs'
          destination_dir: 'docs'
          keep_files: true
