name: flake8

on:
  push:
    branches:
      - '*'

jobs:
  flake8:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.11
          auto-update-conda: true
          activate-environment: moranpycess-dev
          environment-file: environment.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Black & Isort
        shell: bash -l {0}
        run: |
	        black moranpycess/ tests/unit/
	        isort moranpycess/ tests/unit/

      - name: Flake8
        shell: bash -l {0}
        run: flake8 moranpycess/ tests/unit/
