name: pr-lint

on:
  # By default, a workflow only runs when a pull_request's activity type
  # is opened, synchronize, or reopened. We explicity override here so that
  # PR titles are re-linted when the PR text content is edited.
  # _target applies to PR from forks.
  pull_request_target:
    types: [opened, edited, reopened, synchronize]

jobs:

  conventional-title:
    runs-on: ubuntu-latest
    steps:
      - uses: morrisoncole/pr-lint-action@v1.7.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          title-regex: "^(feat|fix|docs|style|refactor|perf|test|build|ci|chore): .{1,}"
          on-failed-regex-fail-action: true
          on-failed-regex-create-review: true
          on-failed-regex-request-changes: true
          on-failed-regex-comment:
            "Please stick to Conventional Commits syntax for PR titles ;)"
          on-succeeded-regex-dismiss-review-comment:
            "Thank you <3"
