name: publish

on:
  push:
    tags:
      - '*'

jobs:

  PyPI:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pypa/build
        run: python -m pip install build --user

      - name: Build a binary wheel and a source tarball
        run: python -m build --sdist --wheel --outdir dist/ .

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

  Anaconda:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Publish to Anaconda Cloud
        uses: m0nhawk/conda-package-publish-action@master
        with:
          subDir: '.'
          AnacondaUsername: ${{ secrets.ANACONDA_USERNAME }}
          AnacondaPassword: ${{ secrets.ANACONDA_PASSWORD }}

  DockerHub:
    runs-on: ubuntu-20.04

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build & Publish image to DockerHub
        env: 
          docker_username: ${{ secrets.DOCKER_USERNAME }}
          docker_password: ${{ secrets.DOCKER_PASSWORD }}
        run: |  
          repo_name="moranpycess"
          tag=${GITHUB_REF##*/}
          echo $repo_name
          echo $tag
          tag="${tag:1}"
          echo $tag
