name: pytest

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  pytest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, ubuntu-20.04]

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Miniconda & Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          auto-update-conda: true
          activate-environment: moranpycess-dev
          environment-file: env/dev.yml
          auto-activate-base: false

      - name: Conda Info
        shell: bash -l {0}
        run: |
          conda info -a
          conda list

      - name: Unit-Test + Coverage
        shell: bash -l {0}
        run: |
          coverage run -m pytest tests/unit/Individual.py tests/unit/MoranProcess.py tests/unit/MoranProcess2D.py tests/unit/MoranProcess3D.py
          coverage report -m

      - name: Submit Report to Codecov
        shell: bash -l {0}
        run: |
          CODECOV_TOKEN=${{ secrets.CODECOV_TOKEN }}
          bash <(curl -s https://codecov.io/bash)
